# ===============================
# DataSource / Database Config
# ===============================
spring.datasource.url=jdbc:postgresql://ep-lively-night-an39auvg-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_uQFqaKg4Df2d
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate Config
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Thymeleaf Template Config
# ===============================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html